spring.application.name=spring-cloud-config-server

server.port=8888
spring.cloud.config.server.git.uri=https://github.com/kavya-sails/centralized-config.git
encrypt.key=123ASDFSADG123MAS895BF842JG807

spring.config.import=application_qa.properties,application_prod.properties
spring.profiles.active=prod

management.endpoints.web.exposure.include=*

build.version=3.0
contact.name=Kavya
contact.email=kavya@gmail.com
contact.phoneNumber=1234567543,901233423423